routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();



Auth::routes();



Route::group(['middleware'=>'auth'],function(){

    Route::get('/dashboard', 'dashboardController@index')->name('dashboard');

    Route::resource('/categories', 'CategoriesController');
    
    Route::resource('/Tags', 'TagsController');
    

    
    Route::resource('/posts', 'PostsController');
    
    Route::get('/trashed-posts', 'PostsController@trashed')->name('trashed.index');
    
    Route::get('/trashed-posts/{id}', 'PostsController@Restore')->name('trashed.Restore'); 
});
route::middleware(['auth','admin'])->group(function(){
    Route::get('/users', 'UserController@index')->name('users.index');
    // Route::get('/users/create', 'UserController@create')->name('users.create');
    Route::post('/users/{user}/make-admin', 'UserController@makeAdmin')->name('users.make-admin');
    Route::post('/users/{user}/downgrade', 'UserController@downgrade')->name('users.downgrade');;

});


route::middleware(['auth'])->group(function(){
    Route::get('/users/{user}/profile', 'UserController@edit')->name('users.edit');
    Route::post('/users/{user}/profile', 'UserController@update')->name('users.update');
    // Route::get('/users/create', 'UserController@create')->name('users.create');
    // Route::post('/users/{user}/make-admin', 'UserController@makeAdmin')->name('users.make-admin');
    // Route::post('/users/{user}/downgrade', 'UserController@downgrade')->name('users.downgrade');;

});

app/tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\post;
class tag extends Model
{
    protected $fillable = ['name'];
    protected $table = 'tags';
    // protected $guarded = ['name'];
    public function posts(){
        //belongsto لمعرفة اين ينتمي البوست وما هو قسمه
        return $this->belongsToMany(post::class);
        }
        
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\TagRequest;

use App\Tag;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('tags.index')->with('tags', Tag::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagRequest $request)
    {
      Tag::create($request->all());

        session()->flash('success', 'Tag created successfuly');

        return redirect(route('Tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $Tag)
    {
        // dd($tag);
      return view('Tags.create')->with('tag', $Tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TagRequest $request, Tag $Tag)
    {
      $Tag->update([
       'name'=>$request->name
        ]);
        // $tag->save();
        // dd($tag);
        session()->flash('success', 'tag updated successfuly');
        return redirect(route('Tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $Tag)
    {
      $Tag->delete();
      // $tag->save();
      return redirect(route('Tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card card-default">
        <div class="card-header">
            {{ isset($tag) ? "Update Tag" : "Add a new Tag" }}
        </div>
        <div class="card-body">
        <form action="@if(isset($tag))
        {{route('Tags.update',$tag->id)}}
         @else
         {{route('Tags.store')}}
         @endif 
         "method="POST">
                @csrf
                @if (isset($tag))
             
                    @method('PUT')
                @endif
                <div class="form-group">
                    <label for="tag">Tag Name:</label>
                <input type="text" name="name" class="@error('name') is-invalid @enderror form-control"  value="{{ isset($tag) ? $tag->name : "" }}">
                    @error('name')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group">
                    <button class="btn btn-success">
                        {{ isset($tag) ? "Update" : "Add" }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')

@section('content')
    @if (session()->has('error'))
      <div class="alert alert-danger">
        {{ session()->get('error') }}
      </div>
    @endif
    <div class="clearfix">
    <a href="{{ route('Tags.create') }}" class="btn float-right btn-success" style="margin-bottom: 10px">Add tags</a>
    </div>
    <div class="card card-default">
        <div class="card-header">All Tags</div>
        <table class="card-body">
            <table class="table">
                <tbody>
                    @foreach ($tags as $tags)
                    <tr>
                        <td>
                        {{ $tags->name }} <span class="ml-2 badge badge-primary">{{$tags->posts()->count()}}</span>
                        </td>
                        <td>
                            <form class="float-right ml-2" action="{{route('Tags.destroy', $tags->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm">
                                    Delete
                                </button>
                            </form>
                        <a href="{{route('Tags.edit', $tags->id)}}" class="btn btn-primary float-right btn-sm">Edit</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection