routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();



Auth::routes();



Route::group(['middleware'=>'auth'],function(){

    Route::get('/dashboard', 'dashboardController@index')->name('dashboard');

    Route::resource('/categories', 'CategoriesController');
    
    Route::resource('/Tags', 'TagsController');
    

    
    Route::resource('/posts', 'PostsController');
    
    Route::get('/trashed-posts', 'PostsController@trashed')->name('trashed.index');
    
    Route::get('/trashed-posts/{id}', 'PostsController@Restore')->name('trashed.Restore'); 
});
route::middleware(['auth','admin'])->group(function(){
    Route::get('/users', 'UserController@index')->name('users.index');
    // Route::get('/users/create', 'UserController@create')->name('users.create');
    Route::post('/users/{user}/make-admin', 'UserController@makeAdmin')->name('users.make-admin');
    Route::post('/users/{user}/downgrade', 'UserController@downgrade')->name('users.downgrade');;

});


route::middleware(['auth'])->group(function(){
    Route::get('/users/{user}/profile', 'UserController@edit')->name('users.edit');
    Route::post('/users/{user}/profile', 'UserController@update')->name('users.update');
    // Route::get('/users/create', 'UserController@create')->name('users.create');
    // Route::post('/users/{user}/make-admin', 'UserController@makeAdmin')->name('users.make-admin');
    // Route::post('/users/{user}/downgrade', 'UserController@downgrade')->name('users.downgrade');;

});

app/post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\category;
use App\tag;
use App\user;
class post extends Model
{
    use SoftDeletes;
    protected $fillable = ['user_id','category_id','image' , 'content' , 'description' , 'title'];
    public function user(){
        //belongsto لمعرفة اين ينتمي البوست وما هو قسمه
        return $this->belongsTo(user::class);

        }
    
    public function Category(){
        //belongsto لمعرفة اين ينتمي البوست وما هو قسمه
        return $this->belongsTo(Category::class);

        }
        public function Tags(){
            //belongstoMany لمعرفة اين ينتمي البوست وما هو قسمه يمكن استخدام علاقة ماني تو ماني في اي جزء وع اي بوست 
            return $this->belongsToMany(tag::class);
            }

            public function hasTag($tagId){
               //in_array تستخدم لان الداتا في اللرافيل ترجع في شكل مصفوفة والبليك تستخدم لارجاع عمود واحد
                return in_array($tagId,$this->tags->pluck('id')->toArray());
               
            }
                   
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Storage;
use App\post;
use App\tag;
use App\category;
use App\Http\Requests\PostRequest;
use App\Http\Requests\UpdatePost;
class PostsController extends Controller
{
    public function __construct()
    {

        $this->middleware('cheeckCategory')->except('index');
    }
    /**
     * 
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('posts.index')->with('posts',post::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create')->with('categories',Category::all())->with('tags',tag::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        // dd($request->Tags);
        // session()->flash('success','Posts Added Successfully');
       
        $post = Post::create([
        'title'=>$request->title,
        'content'=>$request->content,
        'description'=>$request->description,
        'image'=>$request->image->store('images','public'),
        'category_id'=> $request->categoryId,
        'user_id'=>$request->user_id
        ]);
        if ($request->tags) {
            $post->Tags()->attach($request->tags);

        }
        session()->flash('success','Post added successfully');
       
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(post $post){
    $user = $post->user;
    $profile = $user->profile;
    return view("posts.show")->with('post',$post)->with('categories',Category::all())->with('profile',$profile)->with('user',$user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post,category $categories )
    {
        return view('posts.create',['Post'=>$post,'tags'=>tag::all(),'categories'=>Category::all()]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePost $request, post $post)

    {
        
        $data= $request->only(['title','content','description']);
        if ($request->HasFile('image')) {
            $image= $request->image->store('image');
            Storage::disk('public')->delete($post->image);
            $data['image']= $image;
        }

        if ($request->tags) {
            $post->tags()->sync($request->tags);
            
        }
        
        $post->update($data);
        session()->flash('success','Post updated successfully');
        return redirect(route('posts.index'));
    }
    

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
  
        $post=post::withTrashed()->where('id',$id)->first();
        if ($post->trashed()) {
            $post->forceDelete();
        
        }else {
            $post->delete();

        };
        session()->flash('success','Post deleted successfully');
        return redirect(route('posts.index'));
    }



    public function trashed()
    {
         $trashed = Post::onlyTrashed()->get();
        return view('posts.index')->withPosts($trashed);
    }
    public function Restore($id){
        post::withTrashed()->where('id',$id)->restore();
        session()->flash('success','Post restored successfully');
        return redirect(route('posts.index'));
    
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')
@section('stylesheets')
<link href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.0/trix.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
@endSection
@section('content')
@if(session()->has('error'))
              <div class="alert alert-danger">
                {{session()->get('error')}}
              </div>
    @endif
<div class="card card-default">
  
  <div class="card-header">
{{isset($post)?       "Edit post" :      "Add a New post" }}

 
  </div>

  <div class="card-body">
    <form  action="{{ isset($post ) ? route('posts.update',$post->id) : route('posts.store')}}"  method="post" enctype="multipart/form-data">
        @csrf
     
        @if(isset($post))
        {{ method_field('put') }}

        @endif

    
        <div class="form-group">
                <label for="title">title</label>
                <input class="  form-control" name="title" type="text" placeholder="Write a Title" name="title" value="{{isset($post)? $post->title : '' }}">
                    @error('title') 
                    <div class="alert alert-danger">
                    {{$message}}
                    </div>
                    @endError
            </div>


            <div class="form-group">
                <label for="content" style="text-align:center">content</label>

                <input id="x" type="hidden" name="content"  class="form-control" value="{{isset($post)? $post->content : '' }}">
  <trix-editor input="x"></trix-editor>
                <!-- <textarea  roe="3"  name="content" class="form-control" rows="5"   placeholder="Write a content"></textarea> -->

                    @error('content') 
                    <div class="alert alert-danger">
                    {{$message}}
                    </div>
                    @endError
            </div>

            <div class="form-group">
                <label for="post">description</label>

                <textarea   row="3" name="description" class="form-control" rows="5"   placeholder="Write a description">{{isset($post) ? $post->description : ''}}</textarea >
              
                    @error('description') 
                    <div class="alert alert-danger">
                    {{$message}}
                    </div>
                    @endError
            </div>
@if(isset($post))
<div class="form-group">
<img src="{{asset('storage/'.$post->image)}}"style="width:100%">
</div>
@endif
            <div class="custom-file">
                <input type="file" class="custom-file-input" name="image" value="{{isset($post)? $post->image : '' }}">
                <label class="custom-file-label" for="image" >Select image</label>
                @error('image') 
                    <div class="alert alert-danger">
                    {{$message}}
                    </div>
                    @endError
            </div>


            <div class="form-group">
          <label for="Selectcategory"> select Category</label>
          <select name="categoryId" class="form-control"  id="categoryId" >

    @foreach($categories  as $category)
            <option value={{$category->id}}>{{$category->name}}</option>
        @endforeach  
        @error('categoryId') 
                    <div class="alert alert-danger">
                    {{$message}}
                    </div>
                    @endError    
          </select>
        </div>

   @if(!$tags->count() <= 0)
   <div class="form-group">
          <label for="SelectcaTag"> select Tag</label>
          <!-- //البراكيتس لحفظ القيمة كا ارري  -->
          <select name="tags[]" class="form-control tags" multiple  >

    @foreach($tags  as $tag)
            <option value={{$tag->id}}
            @if($post->hasTag($tag->id))
            selected
            @endif
            
            >{{$tag->name}}</option>
        @endforeach  
        @error('TagId') 
                    <div class="alert alert-danger">
                    {{$message}}
                    </div>
                    @endError    
          </select>
        </div>
        @endif
<input  type="hidden" name="user_id"  class="form-control" value="{{auth::user()->id}}">
            <div class="form-group">
                <button class="btn btn-primary btn-lg btn-block" style="margin:10px 5px 10px 5px; position:center ">{{isset($post)?       "Edit" :      "Add " }}
                </button>
            </div>
            <!-- <div class="form-group"></div>
            <div class="form-group"></div>
            <div class="form-group"></div> -->
    </form>
  </div>

</div>

@endSection
@section('scripts')




<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.0/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>

    <script>
      $(document).ready(function() {
        $('.tags').select2();
      });
    </script>

@endSection

resources/views/posts/index.blade.php
@extends('layouts.app')

    @section('content')
    @if(session()->has('error'))
              <div class="alert alert-danger">
                {{session()->get('error')}}
              </div>
    @endif
<div class="clearfix">
<a href="{{route('posts.create')}}" class="btn float-right btn-success" style="margin-bottom:10px">Add Post</a>
</div>
    <div class="card card-default">
  
        <div class="card-header">
             <h1>All Posts</h1>
        </div>


<table class="table table-striped">
  <thead>
    <tr>
    <th scope="col">id</th>
      <th scope="col">title</th>
      <th scope="col">content</th>
      <th scope="col">image</th>
      <th scope="col">Actions</th>
     
    </tr>
  </thead>
         @foreach($posts as $post)     
         <tbody>
    <tr>
      <td>{{$post->id}}</td>
      <td>{{$post->title}}</td>
      <td>{{$post->content}}</td>
      <td><img src="{{asset('storage/'.$post->image)}}" width="80px" height="50px"></td>
      <td>
      @if(!$post->trashed())
      <a href="{{route('posts.edit',$post->id)}}" class="btn btn-primary btn-sm">Edit </a>
      @else
      <a href="{{route('trashed.Restore',$post->id)}}" class="btn btn-primary btn-sm">Restore </a>

      @endif
      <form class="float-right" action="{{route('posts.destroy' ,$post->id)}}" method="Post">
      @csrf
      @method('delete')
      <button class="btn btn-danger btn-sm" value="delete">{{$post->trashed() ?'Delete' : 'trash'}} </button>
      </form>
      </td>

    </tr>
  </tbody>
        @endforeach
         </table>

        </div>
    
    </div>


    @endSection