routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();



Auth::routes();



Route::group(['middleware'=>'auth'],function(){

    Route::get('/dashboard', 'dashboardController@index')->name('dashboard');

    Route::resource('/categories', 'CategoriesController');
    
    Route::resource('/Tags', 'TagsController');
    

    
    Route::resource('/posts', 'PostsController');
    
    Route::get('/trashed-posts', 'PostsController@trashed')->name('trashed.index');
    
    Route::get('/trashed-posts/{id}', 'PostsController@Restore')->name('trashed.Restore'); 
});
route::middleware(['auth','admin'])->group(function(){
    Route::get('/users', 'UserController@index')->name('users.index');
    // Route::get('/users/create', 'UserController@create')->name('users.create');
    Route::post('/users/{user}/make-admin', 'UserController@makeAdmin')->name('users.make-admin');
    Route::post('/users/{user}/downgrade', 'UserController@downgrade')->name('users.downgrade');;

});


route::middleware(['auth'])->group(function(){
    Route::get('/users/{user}/profile', 'UserController@edit')->name('users.edit');
    Route::post('/users/{user}/profile', 'UserController@update')->name('users.update');
    // Route::get('/users/create', 'UserController@create')->name('users.create');
    // Route::post('/users/{user}/make-admin', 'UserController@makeAdmin')->name('users.make-admin');
    // Route::post('/users/{user}/downgrade', 'UserController@downgrade')->name('users.downgrade');;

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use post;
class Category extends Model
{
 protected $fillable =['name'];
 public function posts(){
    return $this->hasmany(post::class);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category as categories;
use App\Http\Requests\category;

class CategoriesController extends Controller
{
   
    public function index()
    {
        //لتمرير الموديل كا متغير
        return view('categories.index')->with('categories', categories::all());
    }

  
    public function create()
    {
        return view('categories.create');
    }

  
    public function store(category $request)
    {
     
   
        categories::create($request->all());
        session()->flash('success','category added successfully');
    return redirect(route('categories.index'));
    }

  
    public function edit(categories  $category)
    {
        return view('categories.create')->with('category',$category);
    }
 
    public function update(Request $request, categories $category)
    {
        $category->update([
           "name"=> $request->name

        ]); 
        // $category->save();
        session()->flash('success','category updated successfully');
       
    return redirect(route('categories.index'));
    }

   
  
    public function destroy( categories $category)
    {
        $category->delete();
         // $category->save();
         session()->flash('success','category deleted successfully');
        
     return redirect(route('categories.index'));
     
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card card-default">
  
  <div class="card-header">
{{isset($category)?       "Edit Category" :      "Add a New Category" }}

 
  </div>

  <div class="card-body">
        <form action="{{isset($category) ? route('categories.update',$category->id) : route('categories.store')}}" method="post">
        @csrf
        @if(isset($category))
        @method('put')
        @endif
            <div class="form-group">
                <label for="category">Category Name</label>
                <input class="@error('name') is-invalid @endError form-control" name="name" type="text" placeholder="add a new category" value="{{isset($category) ? $category->name : '' }}">
                    @error('name') 
                    <div class="alert alert-danger">
                    {{$message}}
                    </div>
                    @endError
            </div>
            <div class="form-group">
                <button class="btn btn-success">{{isset($category)?       "Edit" :      "Add " }}
</button>
            </div>
            <!-- <div class="form-group"></div>
            <div class="form-group"></div>
            <div class="form-group"></div> -->
        </form>
  </div>

</div>

@endSection

resources/views/categories/index.blade.php
@extends('layouts.app')

    @section('content')
<div class="clearfix">
<a href="categories/create" class="btn float-right btn-success" style="margin-bottom:10px">Add Category</a>
</div>
    <div class="card card-default">
  
        <div class="card-header">
             <h1>All Categories Is HERE</h1>
        </div>


<table class="table table-striped">
  <thead>
    <tr>
    <th scope="col">id</th>
      <th scope="col">name</th>
      <th scope="col">Time of Creating</th>
      <th scope="col">Edit Category</th>
      <th scope="col">Delete Category</th>
    </tr>
  </thead>
         @foreach($categories as $category)     
         <tbody>
    <tr>
      <td>{{$category->id}}</td>
      <td>{{$category->name}}</td>
      <td>{{$category->created_at}}</td>
      <td><a href="{{route('categories.edit',$category->id)}}" class="btn btn-primary btn-small">Edit category</a></td>
      <form class="float-right" action="{{route('categories.destroy' ,$category->id)}}" method="Post">
      @csrf
      @method('delete')
      <td>
      <button class="btn btn-danger btn-small" value="delete">Delete Category</button>
      </td>
      </form>
    </tr>
  </tbody>
        @endforeach
         </table>

        </div>
    
    </div>


    @endSection